kind: Deployment
apiVersion: apps/v1
metadata:
  name: menu-api
  namespace: sample-application
  labels:
    app: menu-api
    app.kubernetes.io/component: menu-api
    app.kubernetes.io/instance: menu-api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: menu-api
  template:
    metadata:
      labels:
        deployment: menu-api
    spec:
      containers:
        - name: menu-api
          image: >-
            image-registry.openshift-image-registry.svc:5000/sample-application/menu-api:latest
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: menu-api
  namespace: sample-application
  labels:
    app: menu-api
    app.kubernetes.io/component: menu-api
    app.kubernetes.io/instance: menu-api
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    deployment: menu-api
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: menu-api
  namespace: sample-application
  labels:
    app: menu-api
    app.kubernetes.io/component: menu-api
    app.kubernetes.io/instance: menu-api
spec:
  to:
    kind: Service
    name: menu-api
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None