apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  workspaces: # Task間のデータの受け渡しはworkspaceにて実施
    - name: shared-workspace
  params: # 各Taskで利用されるパラメータを定義
    - name: url
      type: string
    - name: SONAR_HOST_URL
      type: string
    - name: SONAR_PROJECT_KEY
      type: string
    - name: IMAGE
      type: string
  tasks:
    - name: git-clone
      taskRef: # Pipelineで実行するTaskの参照先
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: sonarqube-scanner
      taskRef:
        name: sonarqube-scanner
      runAfter: # あるTaskが実行された後に本Taskが実行されるよう順番を制御
        - git-clone
      params:
        - name: SONAR_HOST_URL
          value: $(params.SONAR_HOST_URL)
        - name: SONAR_PROJECT_KEY
          value: $(params.SONAR_PROJECT_KEY)
      workspaces:
        - name: source-dir
          workspace: shared-workspace
        - name: sonar-settings
          workspace: sonar-settings
    - name: buildah
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
        - sonarqube-scanner
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace