apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-pipeline-run
  namespace: sample-application
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: s2i-build-and-deploy
  params:
    - name: IMAGE_NAME
      value: >-
        image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/sample-api
    - name: GIT_REPO
      value: 'https://gitea-instance-gitea.apps.cluster-s45fh.s45fh.sandbox2386.opentlc.com/jiadchen/openshift-pipeline-springboot.git'
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
